services:
    crewcall.jobs:
        class: CrewCallBundle\Service\Jobs
        arguments: ["@doctrine.orm.entity_manager"]

    crewcall.retriever:
        class: CrewCallBundle\Service\CrewCallRetriever
        arguments: ["@doctrine.orm.entity_manager"]

    crewcall.calendar:
        class: CrewCallBundle\Service\Calendar
        arguments: ["@router"]

    crewcall.formcreator:
        class: CrewCallBundle\Service\FormCreator
        arguments: ["@service_container"]

    crewcall_retriever:
        alias: crewcall.retriever
